### ISSUE TITLE
separate strategy from task in yaml file

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/tricolour#14]
Use `cfg` here instead of global dict.

I think the layout of the configuration options in the config file should change. I would favour something as follows:

```yaml
strategy:
  pipeline: ['apply_static_mask', 'sum_threshold']

tasks:
   apply_static_mask:
      option1: ...
      option2: ...
   sum_threshold:
      option1: ...
      option2: ...
```

Then you can do:

```python
for task in cfg['strategy']['pipeline]:
  task_cfg = cfg['tasks'][task]
```

For the future (not this PR)  perhaps this also means we should start working out how to specify strategies. I might favour a python script.

_Originally posted by @sjperkins in https://github.com/ska-sa/tricolour/pull/12_
